gatling {

  core {

    outputDirectoryBaseName = "results"

    directory {
      results = "/opt/gatling/results"
    }
  }

  charting {
    noReports = false
    useGroupDurationMetric = false
  }
}